export enum ECategory {
  MUSIC = 'Musique',
  CONFERENCE = 'Conférence',
  WORKSHOP = 'Atelier / Formation',
  SPORT = 'Sport',
  FESTIVAL = 'Festival',
  EXHIBITION = 'Exposition',
  NETWORKING = 'Réseautage / Rencontre',
  THEATER = 'Théâtre / Spectacle',
  RELIGIOUS = 'Religion / Spiritualité',
  COMMUNITY = 'Communautaire',
  FOOD = 'Gastronomie / Dégustation',
  TECHNOLOGY = 'Technologie / Innovation',
  EDUCATION = 'Éducation / Universitaire',
  HEALTH = 'Santé / Bien-être',
  MOVIE = 'Cinéma / Projection',
  CHARITY = 'Caritatif / Humanitaire',
  OTHER = 'Autre',
}
